// ============================================================================
// Build the Android APK.
//
//   node scripts/android-apk.mjs              # debug APK from build/android-www
//   node scripts/android-apk.mjs --release    # unsigned release APK
//
// Run `npm run android:app` or `npm run android:player <bake>` first — this
// assembles whatever is currently in `build/android-www`.
//
// WHY THIS SCRIPT EXISTS
//
// `android/` is generated by `npx cap add android` and is gitignored, so it is
// disposable by design: delete it, re-add it, and you must get the same app
// back. That means no hand-edit of the native project may ever be load-bearing
// — every one of them lives here, applied idempotently before the build. If
// you find yourself editing a file under `android/`, put it here instead or it
// will vanish the next time someone regenerates the project.
//
// Two things bite on a fresh Windows machine, both handled below:
//
//   • The SDK that Visual Studio installs lives under Program Files and is
//     READ-ONLY. Anything AGP decides to download into it fails.
//   • AGP picks its own default build-tools version and downloads it. Pinning
//     every module to what is actually installed means it downloads nothing,
//     which also sidesteps SDK licences having been accepted by another user.
// ============================================================================
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { readSecret, SECRET } from './signing-secret.mjs';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const androidDir = path.join(root, 'android');

/** The Android SDK, in the order a Windows box is likely to have one. */
function findSdk() {
  const candidates = [
    process.env.ANDROID_HOME,
    process.env.ANDROID_SDK_ROOT,
    process.env.LOCALAPPDATA && path.join(process.env.LOCALAPPDATA, 'Android', 'Sdk'),
    'C:\\Program Files (x86)\\Android\\android-sdk',
  ].filter(Boolean);
  for (const c of candidates) if (fs.existsSync(path.join(c, 'platforms'))) return c;
  throw new Error(
    'no Android SDK found. Set ANDROID_HOME, or install one via Android Studio / the Visual Studio "Mobile development" workload.',
  );
}

/** Newest installed build-tools. Pinning to this is what stops AGP downloading. */
function newestBuildTools(sdk) {
  const dir = path.join(sdk, 'build-tools');
  if (!fs.existsSync(dir)) throw new Error(`no build-tools in ${sdk} — install at least one via sdkmanager`);
  const versions = fs.readdirSync(dir).filter((n) => /^\d+/.test(n));
  if (!versions.length) throw new Error(`no build-tools in ${dir}`);
  const key = (v) => v.split('.').map((n) => parseInt(n, 10) || 0);
  versions.sort((a, b) => {
    const [x, y] = [key(a), key(b)];
    for (let i = 0; i < 3; i++) if ((x[i] ?? 0) !== (y[i] ?? 0)) return (y[i] ?? 0) - (x[i] ?? 0);
    return 0;
  });
  return versions[0];
}

/** A JDK 17+ for Gradle. Java 8 on PATH is the usual trap. */
function findJdk() {
  if (process.env.JAVA_HOME && fs.existsSync(path.join(process.env.JAVA_HOME, 'bin', 'javac.exe'))) return process.env.JAVA_HOME;
  const roots = ['C:\\Program Files\\Java', 'C:\\Program Files\\Eclipse Adoptium', 'C:\\Program Files\\Android\\Android Studio'];
  const hits = [];
  for (const r of roots) {
    if (!fs.existsSync(r)) continue;
    for (const n of fs.readdirSync(r)) {
      const p = path.join(r, n);
      // Android Studio ships its JBR one level down.
      for (const cand of [p, path.join(p, 'jbr')])
        if (fs.existsSync(path.join(cand, 'bin', 'javac.exe'))) {
          const m = /(\d+)/.exec(n);
          hits.push({ path: cand, major: m ? parseInt(m[1], 10) : 0 });
        }
    }
  }
  // AGP 8.13 supports JDK 17–21. Newer is NOT better here: JDK 23 builds debug
  // fine and then fails `:capacitor-android:compileReleaseJavaWithJavac` with
  // "Illegal UTF8 string in constant pool in class file com/sun/tools/javac/comp/Attr"
  // — javac failing to read its own class file. So prefer the newest supported
  // one, and only fall back to an unsupported one if nothing else exists.
  const supported = hits.filter((h) => h.major >= 17 && h.major <= 21).sort((a, b) => b.major - a.major);
  const any = hits.filter((h) => h.major >= 17).sort((a, b) => b.major - a.major);
  if (!any.length) throw new Error('no JDK 17+ found. Set JAVA_HOME to one (a JRE will not do — Gradle needs javac).');
  if (!supported.length)
    console.warn(
      `WARNING: only JDK ${any[0].major} is installed; AGP supports 17-21. Debug builds work, release may fail.\n` +
        `         Install one with:  winget install EclipseAdoptium.Temurin.21.JDK`,
    );
  return (supported[0] ?? any[0]).path;
}

/** Rewrite `f` through `fn`, but only write when something changed. */
function patch(file, fn) {
  const before = fs.readFileSync(file, 'utf8');
  const after = fn(before);
  if (after !== before) fs.writeFileSync(file, after);
  return after !== before;
}

const MARK = '// livepatch: pinned build-tools';

/**
 * Window theme: dark, fullscreen, and no light flash on launch.
 *
 * The template's `AppTheme.NoActionBarLaunch` parents `Theme.SplashScreen` and
 * never sets `postSplashScreenTheme`, so the activity KEEPS the splash theme
 * for its whole life — and that theme's background is Capacitor's own light
 * splash drawable. It shows as a pale border around the WebView for as long as
 * the app is open, which reads as "the app doesn't fit the screen". Handing the
 * activity a real post-splash theme is the fix.
 *
 * `windowFullscreen` then takes the status bar (clock, battery) out of the
 * layout, and `shortEdges` lets the page paint into the display cutout — this
 * is a control surface you hold in front of you, so every row of pixels the
 * system keeps is a row of faders it costs.
 */
/**
 * Where the release signing details live.
 *
 * Outside the repo, always. A keystore and its passwords are the identity of
 * the app — anything that can update an installed LivePatch is signed with
 * this — so it must not be a file that a stray `git add -A` can publish, and
 * this script never creates one or handles the passwords.
 */
const SIGNING = path.join(process.env.USERPROFILE || process.env.HOME || '.', '.livepatch', 'signing.properties');

const SIGN_MARK = '// livepatch: release signing';

/**
 * Teach `assembleRelease` to sign, if there is a key to sign with.
 *
 * A debug APK is already signed — with the shared debug key every Android SDK
 * on earth has — which is exactly why Play Protect distrusts it. A release key
 * is what makes the install a normal one.
 */
function patchSigning() {
  const gradle = path.join(androidDir, 'app', 'build.gradle');
  const have = fs.existsSync(SIGNING) || !!process.env.LIVEPATCH_STORE_PASSWORD || fs.existsSync(SECRET);
  patch(gradle, (s) => {
    // Replace an older injected block rather than skipping, so changes to the
    // template below actually reach a project that has already been patched.
    if (s.includes(SIGN_MARK)) {
      s = s.replace(new RegExp(`\\n[ \\t]*${SIGN_MARK}[\\s\\S]*?\\n    \\}\\n(?=    buildTypes)`), '\n');
      s = s.replace(/\n        release \{\n            signingConfig signingConfigs\.release\n        \}/, '');
    }
    if (!have) return s;
    // Injected ahead of `buildTypes`, which every Capacitor template has.
    return s.replace(
      /(\n\s*buildTypes\s*\{)/,
      `\n    ${SIGN_MARK}: details come from ${SIGNING.replace(/\\/g, '/')},\n` +
        `    // which lives outside the repo and is never created by the build.\n` +
        `    // The environment wins over the file. A password in a file is a\n` +
        `    // password that gets read — by a backup, a sync client, a support\n` +
        `    // transcript. LIVEPATCH_STORE_PASSWORD lets it live nowhere on disk.\n` +
        `    signingConfigs {\n` +
        `        release {\n` +
        `            def props = new Properties()\n` +
        `            def f = file('${SIGNING.replace(/\\/g, '/')}')\n` +
        `            if (f.exists()) f.withInputStream { props.load(it) }\n` +
        `            def env = System.getenv()\n` +
        `            storeFile file(env['LIVEPATCH_KEYSTORE'] ?: props.getProperty('storeFile'))\n` +
        `            storePassword env['LIVEPATCH_STORE_PASSWORD'] ?: props.getProperty('storePassword')\n` +
        `            keyAlias env['LIVEPATCH_KEY_ALIAS'] ?: props.getProperty('keyAlias') ?: 'livepatch'\n` +
        `            keyPassword env['LIVEPATCH_KEY_PASSWORD'] ?: env['LIVEPATCH_STORE_PASSWORD'] ?: props.getProperty('keyPassword')\n` +
        `        }\n` +
        `    }$1\n` +
        `        release {\n` +
        `            signingConfig signingConfigs.release\n` +
        `        }`,
    );
  });
  return have;
}

function patchTheme() {
  fs.writeFileSync(
    path.join(androidDir, 'app', 'src', 'main', 'res', 'values', 'styles.xml'),
    `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/android-apk.mjs. Edits here are lost on the next build. -->
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:windowBackground">@color/ic_launcher_background</item>
    </style>

    <!-- What the app actually runs under, once the splash is gone. -->
    <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowBackground">@color/ic_launcher_background</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:navigationBarColor">@android:color/transparent</item>
    </style>

    <!-- Android 12+ draws the adaptive icon on a solid colour; no bitmap. -->
    <style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/ic_launcher_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/ic_launcher_foreground</item>
        <item name="postSplashScreenTheme">@style/AppTheme.NoActionBar</item>
    </style>
</resources>
`,
  );
}

function patchNative(sdk, buildTools) {
  fs.writeFileSync(
    path.join(androidDir, 'local.properties'),
    `## Machine-local SDK location. Not committed — every machine's is different.\nsdk.dir=${sdk.replace(/\\/g, '\\\\').replace(/:/g, '\\:')}\n`,
  );

  // Every module, including the ones under node_modules, gets the build-tools
  // that exist on this machine.
  patch(path.join(androidDir, 'build.gradle'), (s) => {
    if (s.includes(MARK)) return s.replace(/(buildToolsVersion = ')[^']+(')/, `$1${buildTools}$2`);
    return (
      s +
      `\n${MARK}: AGP otherwise picks its own default and DOWNLOADS it, which\n` +
      `// fails against a read-only SDK (the one Visual Studio installs under\n` +
      `// Program Files) and against licences accepted by a different user.\n` +
      `subprojects {\n` +
      `    afterEvaluate { p ->\n` +
      `        if (p.hasProperty('android')) p.android.buildToolsVersion = '${buildTools}'\n` +
      `    }\n` +
      `}\n`
    );
  });

  patchTheme();

  // Audio permissions. Capacitor's WebChromeClient answers the WebView's
  // getUserMedia prompt by requesting RECORD_AUDIO at runtime, so declaring it
  // is the whole of what the web layer needs for input blocks to work.
  //
  // Each permission is checked on its own. Gating the whole block on the first
  // one means adding a second permission later is silently a no-op on any
  // machine that has already built once — which is exactly what happened to
  // REQUEST_INSTALL_PACKAGES, and it only showed up in `aapt2 dump badging`.
  const PERMS = [
    ['android.permission.RECORD_AUDIO', 'audio input blocks'],
    ['android.permission.MODIFY_AUDIO_SETTINGS', 'audio routing'],
    // Keeping audio alive with the screen off. Ordinary for an audio app and
    // not a Play Protect trigger, unlike REQUEST_INSTALL_PACKAGES below.
    ['android.permission.FOREGROUND_SERVICE', 'audio with the screen off'],
    ['android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK', 'audio with the screen off (Android 14+)'],
    // Android 13+ requires this before the service's own notification shows.
    // The service still runs without it; the notification is just invisible.
    ['android.permission.POST_NOTIFICATIONS', "the audio service's notification"],
  ];
  // Permissions that must be actively taken OUT. `android/` survives between
  // builds, so dropping one from PERMS above would leave it in place on any
  // machine that had already built with it — the manifest patch only ever adds.
  //
  // REQUEST_INSTALL_PACKAGES was here so the app could install its own updates.
  // Play Protect answered with **Harmful App Blocked** on a real device, with a
  // properly release-signed APK: a sideloaded app from an unrecognised
  // developer asking for the power to install other apps matches the malware
  // profile too closely, and a signing key does not buy reputation. The browser
  // does the download and the install now (androidupdate.ts).
  //
  // FOREGROUND_SERVICE_MEDIA_PROJECTION went the same way when system-audio
  // capture was removed (2026-08-02). Leaving it would be a permission to
  // record other apps' output on a build that has no code to do it — the exact
  // shape of over-permissioning that Play Protect and users are right to
  // distrust.
  const REMOVED_PERMS = [
    'android.permission.REQUEST_INSTALL_PACKAGES',
    'android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION',
  ];
  patch(path.join(androidDir, 'app', 'src', 'main', 'AndroidManifest.xml'), (s) => {
    for (const perm of REMOVED_PERMS) {
      // Takes the comment line above it too, so removal leaves no orphan.
      s = s.replace(new RegExp(`[ \\t]*(<!--[^>]*-->\\s*)?<uses-permission android:name="${perm}"\\s*/>\\r?\\n`, 'g'), '');
    }
    for (const [perm, why] of PERMS) {
      if (s.includes(perm)) continue;
      s = s.replace(
        '<uses-permission android:name="android.permission.INTERNET" />',
        `<uses-permission android:name="android.permission.INTERNET" />\n` +
          `    <!-- ${why} -->\n    <uses-permission android:name="${perm}" />`,
      );
    }
    return s;
  });

  patchService();
  patchJava();
  patchVersion();
}

/**
 * Declare the keep-alive service.
 *
 * A `Service` class that is not in the manifest does not fail to build — it
 * fails at `startForegroundService()`, at runtime, on the device, as a
 * `ClassNotFoundException` nobody sees because the call site swallows it. So
 * this is checked rather than assumed.
 */
function patchService() {
  const manifest = path.join(androidDir, 'app', 'src', 'main', 'AndroidManifest.xml');
  patch(manifest, (s) => {
    if (s.includes('AudioKeepAliveService')) return s;
    return s.replace(
      '    </application>',
      '        <!-- Keeps the process alive so the WebView\'s AudioContext survives\n' +
        '             the screen going off. Started and stopped by the engine. -->\n' +
        '        <service\n' +
        '            android:name=".AudioKeepAliveService"\n' +
        '            android:exported="false"\n' +
        '            android:foregroundServiceType="mediaPlayback" />\n' +
        '    </application>',
    );
  });
  // The system-audio capture service is REMOVED, not merely no longer added.
  // `android/` survives between builds and this patcher only ever appends, so a
  // machine that built before 2026-08-02 would keep a `<service>` pointing at a
  // Java class that no longer exists — which is not a build error, it is an
  // `AndroidManifest` referencing a missing class and a crash on first start.
  //
  // The inner `(?!-->)` and `(?!\/>)` guards are load-bearing. A plain `[^]*?`
  // for the leading comment matched from the KEEP-ALIVE comment's `<!--` all the
  // way to the capture comment's `-->`, swallowing the keep-alive `<service>`
  // in between — so the removal deleted both services and Android audio lost its
  // foreground service. `npm run test:apk` caught it; nothing else would have,
  // until the screen went off on a real phone.
  patch(manifest, (s) =>
    s.replace(
      /[ \t]*(<!--(?:(?!-->)[^])*?-->\s*)?<service\s+android:name="\.SystemAudioCaptureService"(?:(?!\/>)[^])*?\/>\r?\n/g,
      '',
    ),
  );
}

/**
 * The Java that cannot live only in the generated project.
 *
 * `MainActivity` has to register the update plugin, and the plugin itself is
 * ours — both would be lost the next time anyone re-ran `npx cap add android`,
 * so `scripts/android-native/` is the source of truth and this copies it in.
 */
function patchJava() {
  const from = path.join(root, 'scripts', 'android-native');
  const to = path.join(androidDir, 'app', 'src', 'main', 'java', 'com', 'livepatch', 'player');
  fs.mkdirSync(to, { recursive: true });
  for (const f of fs.readdirSync(from)) {
    if (!f.endsWith('.java')) continue;
    fs.copyFileSync(path.join(from, f), path.join(to, f));
  }
}

/**
 * Stamp the APK with package.json's version.
 *
 * The update check compares the running version against the newest GitHub
 * release. Capacitor's template hardcodes `versionName "1.0"`, which would make
 * every release look like a downgrade and the check permanently silent.
 * `versionCode` must be a rising integer, so the dotted version is packed into
 * one: 0.1.4 → 10004.
 */
function patchVersion() {
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  const [maj = 0, min = 0, pat = 0] = String(pkg.version).split('.').map((n) => parseInt(n, 10) || 0);
  const code = maj * 1000000 + min * 10000 + pat;
  patch(path.join(androidDir, 'app', 'build.gradle'), (s) =>
    s.replace(/versionCode\s+\d+/, `versionCode ${code}`).replace(/versionName\s+"[^"]*"/, `versionName "${pkg.version}"`),
  );
}

/**
 * Run a Windows `.bat`/`.cmd` batch file.
 *
 * Node 24 refuses to `spawn` one directly (EINVAL) — the fix for the BatBadBut
 * argument-injection bug — so it has to go through `cmd.exe`. `execFileSync`
 * still quotes each argument, which matters here because the repo path has a
 * space in it.
 */
function runBatch(bat, args, env) {
  execFileSync(process.env.ComSpec || 'cmd.exe', ['/c', bat, ...args], {
    cwd: androidDir,
    stdio: 'inherit',
    env: { ...process.env, ...env },
  });
}

function main() {
  const release = process.argv.includes('--release');
  if (!fs.existsSync(path.join(root, 'build', 'android-www', 'index.html')))
    throw new Error('build/android-www is missing or empty — run "npm run android:app" first');
  if (!fs.existsSync(androidDir)) {
    console.error('android/ does not exist. Create it once with:\n  npx cap add android');
    process.exit(2);
  }

  const sdk = findSdk();
  const buildTools = newestBuildTools(sdk);
  const jdk = findJdk();
  console.log(`SDK         ${sdk}`);
  console.log(`build-tools ${buildTools}`);
  console.log(`JDK         ${jdk}`);

  patchNative(sdk, buildTools);
  const signed = patchSigning();
  console.log(`signing     ${signed ? SIGNING : 'debug key (no ' + SIGNING + ')'}`);
  execFileSync(process.execPath, [path.join(root, 'scripts', 'android-assets.mjs')], { cwd: root, stdio: 'inherit' });
  // The CLI's own JS entry rather than `npx cap` — one less shell between here
  // and the thing being run, and no `.cmd` for Node 24 to refuse.
  execFileSync(process.execPath, [path.join(root, 'node_modules', '@capacitor', 'cli', 'bin', 'capacitor'), 'sync', 'android'], {
    cwd: root,
    stdio: 'inherit',
  });

  const task = release ? 'assembleRelease' : 'assembleDebug';
  const env = { JAVA_HOME: jdk, ANDROID_HOME: sdk };
  // The DPAPI-encrypted password, decrypted straight into Gradle's environment
  // (scripts/signing-secret.mjs). Never onto argv, which is world-readable in
  // the process table, and never into a file. Skipped when the environment
  // already carries one, so an explicit LIVEPATCH_STORE_PASSWORD still wins.
  //
  // The env-wins branch says so OUT LOUD. It used to be silent, and a stale
  // user-scope LIVEPATCH_STORE_PASSWORD left over from an older keystore then
  // beat the correct DPAPI secret on every release build: gradle failed with
  // "keystore password was incorrect", no release APK was produced, and
  // android-install.mjs quietly fell back to the DEBUG apk — which then failed
  // to install with a signing error. Two confusing symptoms, both from one
  // invisible override. Naming the source turns that into one glance.
  if (release) {
    if (process.env.LIVEPATCH_STORE_PASSWORD) {
      console.log(`password    LIVEPATCH_STORE_PASSWORD from the environment (overrides ${SECRET})`);
    } else {
      const secret = readSecret();
      if (secret) {
        env.LIVEPATCH_STORE_PASSWORD = secret;
        console.log(`password    ${SECRET} (DPAPI, this Windows account only)`);
      } else {
        console.log(`password    none — no ${SECRET} and no LIVEPATCH_STORE_PASSWORD`);
      }
    }
  }
  runBatch(path.join(androidDir, 'gradlew.bat'), [task, '--no-daemon'], env);

  const out = path.join(androidDir, 'app', 'build', 'outputs', 'apk', release ? 'release' : 'debug');
  const apk = fs.existsSync(out) ? fs.readdirSync(out).find((n) => n.endsWith('.apk')) : null;
  if (!apk) throw new Error(`gradle reported success but no APK is in ${out}`);
  const full = path.join(out, apk);
  console.log(`\nAPK: ${full}  (${(fs.statSync(full).size / 1024 / 1024).toFixed(1)} MB)`);

  // Also into release/, under the name ship.mjs uploads and the in-app update
  // check looks for. Keeping every shippable artifact in one directory is what
  // lets `npm run ship:resume` re-upload from disk after a failed run.
  //
  // RELEASE BUILDS ONLY. This copy used to be unconditional, so `npm run
  // android:apk` silently replaced the shippable artifact with a DEBUG-signed
  // APK under the release filename — and `ship` would then upload it as the
  // update feed, where no phone could install it (wrong signing key) and
  // nothing in the ship output would say why.
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  if (release) {
    const releaseDir = path.join(root, 'release');
    fs.mkdirSync(releaseDir, { recursive: true });
    const named = path.join(releaseDir, `LivePatch-${pkg.version}.apk`);
    fs.copyFileSync(full, named);
    console.log(`     copied to ${named}`);
  }

  // And into dev/, which is the ONE place a human is asked to look for a build
  // to put on a phone. Automatic because the alternative was proved to fail:
  // dev/ sat for six hours holding two APKs that predated the fixes they were
  // supposed to demonstrate, and the only way to tell was to unzip them and
  // grep. Stale artifacts there are worse than none — they get installed.
  //
  // Every OTHER apk is deleted, not just overwritten. Two builds of different
  // types or versions side by side is exactly the ambiguity this is here to
  // remove, and the debug/release pair cannot even replace each other on a
  // phone (different signing keys).
  const devDir = path.join(root, 'dev');
  fs.mkdirSync(devDir, { recursive: true });
  const devName = `LivePatch-${pkg.version}-${release ? 'release' : 'debug'}.apk`;
  for (const f of fs.readdirSync(devDir)) {
    if (f.endsWith('.apk') && f !== devName) {
      fs.rmSync(path.join(devDir, f));
      console.log(`     dev/: removed stale ${f}`);
    }
  }
  fs.copyFileSync(full, path.join(devDir, devName));
  console.log(`     copied to ${path.join(devDir, devName)}`);
  console.log('Install with:  adb install -r "' + full + '"');
  if (release && !signed) {
    console.log(`\nUNSIGNED — this will not install. Create a key once:\n`);
    console.log(`  keytool -genkeypair -v -keystore "%USERPROFILE%\\.livepatch\\livepatch.jks" \\`);
    console.log(`    -alias livepatch -keyalg RSA -keysize 2048 -validity 10000\n`);
    console.log(`then write ${SIGNING} with storeFile / storePassword / keyAlias / keyPassword.`);
  }
}

main();
